version: '3.8'

services:
  ezlocalai:
    build: 
      context: .
      dockerfile: cuda.Dockerfile
    environment:
      - EZLOCALAI_URL=http://localhost:8091
      - EZLOCALAI_API_KEY=
      - GPU_LAYERS=0
      - MAIN_GPU=0
      - DEFAULT_MODEL=phi-2-dpo
      - LLM_MAX_TOKENS=0
      - WHISPER_MODEL=base.en
      - IMG_ENABLED=false
      - SD_MODEL=stabilityai/sdxl-turbo
      - VISION_MODEL=deepseek-ai/deepseek-vl-1.3b-chat
      - CUDA_DOCKER_ARCH=all
    restart: unless-stopped
    ports:
      - "8091:8091"
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./voices:/app/voices
      - ./whispercpp:/app/whispercpp
      - ./xttsv2_2.0.2:/app/xttsv2_2.0.2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
