version: '3.8'

services:
  ezlocalai:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - EZLOCALAI_URL=${EZLOCALAI_URL-http://localhost:8091}
      - EZLOCALAI_API_KEY=${EZLOCALAI_API_KEY-}
      - MAIN_GPU=${MAIN_GPU-0}
      - DEFAULT_MODEL=${DEFAULT_MODEL-unsloth/Qwen3-VL-4B-Instruct-GGUF}
      - WHISPER_MODEL=${WHISPER_MODEL-base.en}
      - IMG_MODEL=${IMG_MODEL-}
      - LLM_BATCH_SIZE=${LLM_BATCH_SIZE-1024}
      - CUDA_DOCKER_ARCH=all
    restart: unless-stopped
    ports:
      - "8091:8091"
    volumes:
      - ./models:/app/models
      - ./hf:/root/.cache/huggingface/hub
      - ./outputs:/app/outputs
      - ./voices:/app/voices
